# make_table_priority1.R
#
# Emits the journal-ready LaTeX for the aligned deciding-tests table and the
# horizon-18 cost table, reading only the frozen CSVs so every printed cell
# is reproducible from outputs. Run after priority1_inference.R.
#
# Usage (repo root):
#   Rscript scripts/make_table_priority1.R \
#       --run-dir outputs/m4_priority1 --timing-dir outputs/m4_priority1_timing_v2
#
# Writes into --run-dir:
#   table5_deciding_tests.tex   five-horizon blocks for the headline contrasts
#   table_cost_h18.tex          per-policy accuracy, cost, and intervention profile

suppressMessages(source("R/adaptive_update.R"))
suppressMessages(library(data.table))

args <- parse_cli_args()
run_dir <- get_arg(args, "run_dir", default = "outputs/m4_priority1", type = "character")
timing_dir <- get_arg(args, "timing_dir", default = "outputs/m4_priority1_timing_v2", type = "character")

CT <- fread(file.path(run_dir, "contrasts_priority1.csv"))
POL <- fread(file.path(run_dir, "policy_summary_priority1.csv"))
GT <- fread(file.path(run_dir, "repro_gates.csv"))
BE_path <- file.path(run_dir, "cost_breakeven.csv")
BE <- if (file.exists(BE_path)) fread(BE_path) else data.table()
TS_path <- file.path(timing_dir, "timing_summary.csv")
TS <- if (file.exists(TS_path)) fread(TS_path) else data.table()

esc <- function(x) gsub("_", "\\\\_", x)
f4d <- function(x) sprintf("%.4f", x)
f2d <- function(x) sprintf("%.2f", x)
f1d <- function(x) sprintf("%.1f", x)
f3d <- function(x) sprintf("%.3f", x)

# ---------------------------------------------------------------------------
# Table 5: deciding tests at full scale
# ---------------------------------------------------------------------------

blocks <- list(
  list(a = "aicc_gate_cap8_tau0.8", b = "fixed_f8",
       title = "Detector with conservative selector: aicc\\_gate\\_cap8\\_tau0.8 vs fixed\\_f8"),
  list(a = "adaptive_cap8_tau0.8", b = "fixed_f8",
       title = "Validation-winner selector: adaptive\\_cap8\\_tau0.8 vs fixed\\_f8"),
  list(a = "aicc_gate_cap8_tau0.8", b = "adaptive_cap8_tau0.8",
       title = "Selector comparison: aicc\\_gate\\_cap8\\_tau0.8 vs adaptive\\_cap8\\_tau0.8"),
  list(a = "trigg_cap8_tau0.6", b = "fixed_f4",
       title = "Rate-matched monitor: trigg\\_cap8\\_tau0.6 vs fixed\\_f4"),
  list(a = "trigg_cap8_tau0.6", b = "fixed_f8",
       title = "Cap-matched monitor: trigg\\_cap8\\_tau0.6 vs fixed\\_f8")
)

n_series <- unique(CT$n_series)
tex <- c(
  "% Generated by scripts/make_table_priority1.R; do not edit cells by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\small",
  "\\caption{Deciding tests at full scale. Paired per-series mean differences in horizon-$h$ MASE on all",
  paste0(format(max(n_series), big.mark = ","), " horizon-18-eligible M4 monthly series, evaluated at the"),
  "horizon-18 origins so only forecast depth varies across rows. Negative favors the first policy.",
  "Intervals are pointwise percentile bootstrap over series ($B = 10{,}000$); Trim is the 5\\% trimmed",
  "mean; Share is the fraction of series with a strictly negative difference (identical forecasts are",
  "common because the policies share the cap calendar when no trigger fires).}",
  "\\label{tab:deciding-tests-full}",
  "\\begin{tabular}{c r c r r r}",
  "\\toprule",
  "Horizon & Mean & 95\\% CI & $t$ & Trim 5\\% & Share \\\\"
)

for (bl in blocks) {
  rows <- CT[policy_a == bl$a & policy_b == bl$b][order(horizon)]
  if (nrow(rows) == 0L) next
  tex <- c(tex, "\\midrule",
           paste0("\\multicolumn{6}{l}{\\emph{", bl$title, "}} \\\\"),
           "\\addlinespace[2pt]")
  for (r in seq_len(nrow(rows))) {
    tex <- c(tex, paste0(
      rows$horizon[r], " & ", f4d(rows$mean_diff[r]),
      " & $[", f4d(rows$boot_lo[r]), ",\\, ", f4d(rows$boot_hi[r]), "]$",
      " & ", f1d(rows$series_t[r]),
      " & ", f4d(rows$trim5[r]),
      " & ", f3d(rows$share_favors_a[r]), " \\\\"
    ))
  }
}

gate_note <- ""
if (nrow(GT) > 0L && all(GT$status == "PASS")) {
  gate_note <- paste0(
    "The validation-gate and monitor rows reproduce the previously reported full-scale ",
    "horizon-18 values to within ", formatC(max(GT$abs_gap), format = "e", digits = 1), "."
  )
}
tex <- c(tex,
  "\\bottomrule",
  "\\end{tabular}",
  if (nzchar(gate_note)) paste0("\\par\\smallskip\\footnotesize ", gate_note) else NULL,
  "\\end{table}"
)
writeLines(tex, file.path(run_dir, "table5_deciding_tests.tex"))

# ---------------------------------------------------------------------------
# Cost table: accuracy, compute, stability, and intervention profile at h18
# ---------------------------------------------------------------------------

P <- copy(POL)
P[, fired := mean_fire_score + mean_fire_signal]
if (nrow(TS) > 0L) {
  P <- merge(P, TS[, .(policy, rel_time = relative_time, rel_inst = relative_instability)],
             by = "policy", all.x = TRUE)
} else {
  P[, rel_time := NA_real_]
  P[, rel_inst := NA_real_]
}
setorder(P, loss_h18)

ct <- c(
  "% Generated by scripts/make_table_priority1.R; do not edit cells by hand.",
  "\\begin{table}[t]",
  "\\centering",
  "\\small",
  "\\caption{Accuracy, cost, and intervention profile at horizon 18. MASE is the mean per-series",
  "horizon-18 loss on the full eligible set. Relative time and relative instability are anchored at",
  "full updating and measured in a single session on a length-stratified 2{,}000-series subsample,",
  "so every ratio shares identical conditions. Searches count full-window model-form selections",
  "including initialization; Fired is the subset triggered by the monitored signal; Changes counts",
  "origins where the deployed form actually differs from the previous origin.}",
  "\\label{tab:cost-h18}",
  "\\begin{tabular}{l r r r r r r}",
  "\\toprule",
  "Policy & MASE(18) & Rel.\\ time & Rel.\\ instab. & Searches & Fired & Changes \\\\",
  "\\midrule"
)
for (r in seq_len(nrow(P))) {
  ct <- c(ct, paste0(
    esc(P$policy[r]), " & ", f4d(P$loss_h18[r]),
    " & ", ifelse(is.finite(P$rel_time[r]), f3d(P$rel_time[r]), "--"),
    " & ", ifelse(is.finite(P$rel_inst[r]), f3d(P$rel_inst[r]), "--"),
    " & ", f2d(P$mean_searches[r]),
    " & ", f2d(P$fired[r]),
    " & ", f2d(P$mean_form_changes[r]), " \\\\"
  ))
}
be_note <- ""
if (nrow(BE) > 0L && all(is.finite(BE$alpha_star))) {
  parts <- vapply(seq_len(nrow(BE)), function(i) {
    paste0(esc(BE$policy_a[i]), " beats ", esc(BE$policy_b[i]),
           " in the composite $C = L + \\alpha T$ whenever $\\alpha < ",
           signif(BE$alpha_star[i], 2), "$")
  }, character(1))
  be_note <- paste0(paste(parts, collapse = "; "), ".")
}
ct <- c(ct,
  "\\bottomrule",
  "\\end{tabular}",
  if (nzchar(be_note)) paste0("\\par\\smallskip\\footnotesize ", be_note) else NULL,
  "\\end{table}"
)
writeLines(ct, file.path(run_dir, "table_cost_h18.tex"))

message("Wrote table5_deciding_tests.tex and table_cost_h18.tex under ", run_dir)
